#!/command/with-contenv /bin/bash

source /assets/functions/00-container
prepare_service defaults single
PROCESS_NAME="postfix"

check_container_initialized
check_service_initialized init
liftoff

print_start "Starting postfix"
exec /usr/sbin/postfix -c /etc/postfix start-fg
