#!/usr/bin/with-contenv /bin/bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="postfix-relay"

check_container_initialized
check_service_initialized init
liftoff

print_info "Starting postfix"
exec /usr/sbin/postfix -c /etc/postfix start-fg
