#!/command/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/03-monitoring
prepare_service
PROCESS_NAME="postfix"

setup_container_mode
configure_fail2ban_postfix
configure_filesystem
configure_ldap
configure_postfix_main
configure_postfix_master
configure_postfix_sasl
configure_postsrsd
configure_tls
check_availability
custom_scripts

liftoff