#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="postfix"


## Postfix Configuration
if var_false "$ENABLE_ZABBIX" ; then rm -rf /assets/cron/crontab.txt; fi;
if var_true "$ENABLE_LDAP" ; then configure_ldap; fi;
certificates dhparam
certificates "${TLS_SERVER_CERT_FILE}"
configure_data_dir
configure_ldap
configure_postfix_main
configure_postfix_master
configure_postfix_postscreen
configure_postfix_sasl
configure_relay_host
lmtp_ready
rspam_ready

postalias /etc/postfix/aliases
touch "${DATA_LOCATION}"sender_domain_checks
postmap "${DATA_LOCATION}"sender_domain_checks

echo "${SERVER_NAME}" > /etc/mailname

if var_true ${ENABLE_TRANSPORT_MAP} ; then
    if [ ! -f ${DATA_LOCATION}${TRANSPORT_MAP} ]; then
        touch ${DATA_LOCATION}${TRANSPORT_MAP}
    fi
    if [ ! -f ${DATA_LOCATION}${TRANSPORT_MAP}.db ] ; then
        postmap ${DATA_LOCATION}${TRANSPORT_MAP}
    fi
fi

### Execute Custom Scripts if exist to modify parts of the system
if [ -d /assets/custom-scripts/ ] ; then
  print_warn "Found Custom Scripts to Execute"
  for f in $(find /assets/custom-scripts/ -name \*.sh -type f); do
    print_warn "Running Script ${f}"
    chmod +x "${f}"
    ${f}
  done
fi

liftoff