#!/command/with-contenv /bin/bash

source /assets/functions/00-container
prepare_service both all
PROCESS_NAME="sasl-authd"

check_container_initialized
liftoff

print_start "Starting SASL Authentication Daemon"
silent exec /usr/sbin/saslauthd -a ${sasl_auth_type} \
                                -O ${sasl_mech_options} \
                                -c \
                                -r \
                                -n 0 \
                                -d ${SASLAUTH_EXTRA_ARGS}

