#!/usr/bin/with-contenv /bin/bash

source /assets/functions/00-container

PROCESS_NAME="rsyslog"
check_container_initialized
check_service_initialized init
liftoff

print_info "Starting rsyslogd"
silent exec rsyslogd -n
